# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               ShankarGarg Blog
tagline:             "Share your knowledge. It’s a way to achieve immortality" – Dalai Lama, "Create a blog, First Step towards immortality" – Shankar Garg
url:                 http://shankargarg.github.io/
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Shankar Garg
  url:               https://in.linkedin.com/in/shnakeygarg
  email:             shnakey.garg@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/ShankarGarg/ShankarGarg.github.io.git
